global using Autofac;
global using TgBusinessLogic.Contracts;
global using TgBusinessLogic.Models;
global using TgBusinessLogic.Services;
global using TgBusinessLogicTests.Common;
global using TgStorage.Contracts;
global using TgStorage.Domain;
global using TgStorage.Utils;
global using TgStorageTests.Common;
