name: Branch Preview Build

on:
  push:
    branches:
      - preview
    paths:
      - '**.csproj'
      - '**.razor'
      - '**.cs'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.2
  
      - name: Setup Nuget Cache
        uses: actions/cache@v3.2.0
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: Install dependencies
        run: nuget restore TgDownloader.sln

      - name: Build app for Release Any CPU
        run: msbuild TgDownloader.sln -t:rebuild -verbosity:quiet -property:Configuration=Release -property:Platform="Any CPU"
