name: Branch Main Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_ACTIONS: true
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2.0.0
        with:
            vs-prerelease: true
      - name: Build app for Release OpenTgResearcherConsole
        run: msbuild Presentation\OpenTgResearcherConsole\OpenTgResearcherConsole.csproj -t:rebuild -verbosity:quiet -property:Configuration=Release -property:Platform="x64"
      - name: Build app for Release OpenTgResearcherDesktop
        run: msbuild Presentation\OpenTgResearcherDesktop\OpenTgResearcherDesktop.csproj -t:rebuild -verbosity:quiet -property:Configuration=Release -property:Platform="x64"
